import type { ApprovalStep, RfaStatus } from './types';

export const APP_VERSION = '1.0.0';

export const SHEETS = {
  USERS: ['USER_ID', 'FULL_NAME', 'EMAIL', 'DEPARTMENT_ID', 'POSITION', 'CAN_CREATE_RFA', 'CAN_APPROVE_RFA', 'IS_ADMIN', 'ACTIVE', 'CREATED_AT', 'UPDATED_AT'],
  DEPARTMENTS: ['DEPARTMENT_ID', 'DEPARTMENT_NAME', 'DEPARTMENT_CODE', 'ACTIVE', 'CREATED_AT', 'UPDATED_AT'],
  APPROVAL_MATRIX: ['MATRIX_ID', 'DEPARTMENT_ID', 'APPROVAL_STEP', 'APPROVER_USER_ID', 'SEQUENCE', 'REQUIRED', 'ACTIVE', 'CREATED_AT', 'UPDATED_AT'],
  RFA: ['RFA_ID', 'RFA_NUMBER', 'DATE_FILED', 'DEPARTMENT_ID', 'DEPARTMENT_NAME', 'REQUESTED_BY', 'REQUESTER_EMAIL', 'POSITION', 'REQUEST_TITLE', 'PURPOSE', 'BUDGET_ALLOCATION', 'TARGET_DATE', 'JUSTIFICATION', 'STATUS', 'CURRENT_STEP', 'CURRENT_APPROVER_USER_ID', 'CURRENT_APPROVER_EMAIL', 'CURRENT_MATRIX_ID', 'RESUME_MATRIX_ID', 'CREATED_AT', 'UPDATED_AT', 'SUBMITTED_AT', 'COMPLETED_AT', 'VERSION'],
  RFA_APPROVALS: ['APPROVAL_ID', 'RFA_ID', 'RFA_NUMBER', 'STEP', 'APPROVER_USER_ID', 'APPROVER_NAME', 'APPROVER_EMAIL', 'ACTION', 'REMARKS', 'TIMESTAMP'],
  RFA_ATTACHMENTS: ['ATTACHMENT_ID', 'RFA_ID', 'FILE_NAME', 'DRIVE_FILE_ID', 'MIME_TYPE', 'SIZE_BYTES', 'UPLOADED_BY', 'UPLOADED_AT'],
  RFA_AUDIT: ['LOG_ID', 'RFA_ID', 'ACTOR_NAME', 'ACTOR_EMAIL', 'ACTION', 'PREVIOUS_STATUS', 'NEW_STATUS', 'REMARKS', 'TIMESTAMP', 'METADATA_JSON'],
  NOTIFICATIONS: ['NOTIFICATION_ID', 'RFA_ID', 'RECIPIENT', 'RECIPIENT_EMAIL', 'NOTIFICATION_TYPE', 'SUBJECT', 'SENT_AT', 'STATUS', 'ERROR_MESSAGE', 'RETRY_COUNT'],
  SETTINGS: ['KEY', 'VALUE', 'DESCRIPTION', 'UPDATED_AT']
} as const;

export const APPROVAL_STEPS: ApprovalStep[] = [
  'PREPARED_BY',
  'RECOMMENDING_APPROVAL',
  'REVIEWED_AND_NOTED',
  'APPROVED_BY'
];

export const STATUS: Record<RfaStatus, RfaStatus> = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  PENDING_RECOMMENDING_APPROVAL: 'PENDING_RECOMMENDING_APPROVAL',
  PENDING_REVIEW: 'PENDING_REVIEW',
  PENDING_AUTHORITY_APPROVAL: 'PENDING_AUTHORITY_APPROVAL',
  RETURNED: 'RETURNED',
  DISAPPROVED: 'DISAPPROVED',
  APPROVED: 'APPROVED',
  IMPLEMENTATION: 'IMPLEMENTATION',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  EXCEPTION: 'EXCEPTION'
};

export const STEP_STATUS: Record<ApprovalStep, RfaStatus> = {
  PREPARED_BY: 'SUBMITTED',
  RECOMMENDING_APPROVAL: 'PENDING_RECOMMENDING_APPROVAL',
  REVIEWED_AND_NOTED: 'PENDING_REVIEW',
  APPROVED_BY: 'PENDING_AUTHORITY_APPROVAL'
};

export const DEFAULT_SETTINGS = [
  ['APP_NAME', 'eRFA', 'Application display name'],
  ['GOOGLE_CLIENT_ID', '', 'OAuth web client ID used to verify Google ID tokens'],
  ['ALLOWED_DOMAIN', '', 'Optional Google Workspace domain restriction'],
  ['FRONTEND_URL', '', 'Published GitHub Pages application URL'],
  ['ATTACHMENT_ROOT_FOLDER_ID', '', 'Drive root folder ID; created by setupDatabase when blank'],
  ['MAX_ATTACHMENT_BYTES', '10000000', 'Maximum attachment size in bytes'],
  ['EMAIL_ENABLED', 'TRUE', 'Send real email notifications through MailApp'],
  ['LAST_RFA_YEAR', '0', 'Internal numbering state'],
  ['LAST_RFA_SEQUENCE', '0', 'Internal numbering state']
] as const;

export const ALLOWED_ATTACHMENT_TYPES = [
  'application/pdf',
  'image/jpeg',
  'image/png',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
];

